### PR TITLE
Add a persistent command history to the CLI

### PR DESCRIPTION
**Pull request by IAmMarcelJung**
This adds a persistent command history to the CLI, which is also available after closing and restarting the CLI.
Adapted from this [stackoverflow post](https://stackoverflow.com/questions/39495024/persistent-history-in-python-cmd-module).

### CODE REVIEW

**Comment by KelvinChung2000** [comment]
I will suggest storing the history in the `.FABulous` folder. So, each project can have its own CLI history.

**Comment by IAmMarcelJung** [comment]
Nice suggestion! It is now implemented.

**Comment by KelvinChung2000** [comment]
We will not need the `.fabulous_history` in the `.gitignore` file then.

**Comment by IAmMarcelJung** [comment]
Ah, yes of course. Fixed!

**Pull request merged**
