### PR TITLE
Add new print feature

### PR DESCRIPTION
**Pull request by KelvinChung2000**
Allow users to print the Bel and Tile information in the loaded fabric.

Some extra clean up.

### CODE REVIEW

**Comment by IAmMarcelJung** [comment]
A lot of docstrings where removed. Was this on done on purpose?

**Comment by IAmMarcelJung** [comment]
Okay then it's fine, just wanted to be sure :)

**Comment by KelvinChung2000** [comment]
If the rest looks good to you, I will merge this in

**Comment by IAmMarcelJung** [comment]
Yes I think it looks good, also tried it out and it worked fine!

**Pull request merged**
